### ISSUE TITLE
Radiation still active in new game save file when disconnect mid game

### ISSUE THREAD

**Issue by DigitalIver** [gamehog44/LethalRadiation#4]
After disconnecting mid game, the radiation effect still active even when i create a new game

**Comment by gamehog44** [comment]
Corrected in commit ff0fb56abf1c35b0095b4301baa042fc4df05ac8.

**Comment by gamehog44** [comment]
Corrected with commit ff0fb56abf1c35b0095b4301baa042fc4df05ac8.
