### ISSUE TITLE
Desync Issue in the Last Version

### ISSUE THREAD

**Issue by SrMoroxide** [gamehog44/LethalRadiation#5]
I played with 2 friends, 2 died and 1 picked up the Apparatus and died trying to leave the facility.
Upon returning to the same planet and entering the facility, the two players who died before picking up the device continue to receive damage periodically along with the blur.
While the player who picked up the Apparatus does not perceive these effects.

**Comment by gamehog44** [comment]
Thanks for the report! Which player pulled the lever to land on the planet the second time?

**Comment by DigitalIver** [comment]
> Thanks for the report! Which player pulled the lever to land on the planet the second time?

i was the host that mostly pulled the lever

**Comment by DigitalIver** [comment]
it only happen to my friend though but not me

**Comment by gamehog44** [comment]
My assumption is that whomever pulls the lever has the status reset but the others do not. I will try to look into this later today.

**Comment by Temmie3754** [comment]
I also experienced what I believe is the same issue where the radiation was present in the facility for some members of the group even on different moons after I had removed the apparatus in a previous run.

**Comment by gamehog44** [comment]
Corrected in commit ecc0043861d2df3b185d3ce5546751dd279202f0.
