### ISSUE TITLE
[BUG] Took the Apparatus on March and nobody received radiation

### ISSUE THREAD

**Issue by Dantoresco** [gamehog44/LethalRadiation#6]
Basically what I said on the tittle, ever since the 1.2.0 update I took the Apparatus 2 times on big lobbies with 4-6 people, nobody perceived the damage of the radiation, no blur effect either. Before this update it was working fine. 
Last time it happened was on March map, the previous time I cannot recall which map we were playing

**Comment by gamehog44** [comment]
Thanks for the report. I am aware of this issue and looking into it as we speak.

**Comment by gamehog44** [comment]
Corrected in commit ecc0043861d2df3b185d3ce5546751dd279202f0.
