### ISSUE TITLE
Is there a way to block apparatus value override?

### ISSUE THREAD

**Issue by Roobotics** [gamehog44/LethalRadiation#9]
At current, with mods like 'Balanced_Items' alongside this one, very unpredictable results have been happening because this one forces an apparatus value on sell, is there a way to not have it patch a value in, so other mods don't have issues? I actually want this to run alongside LethalMeltdown, the blur and slight damage are a great touch, but the apparatus patching is fighting other things, Meltdown has an option to set a 'False' flag for 'OverrideApparatusValue'

Do you support anything like a '-1' value to bypass your forced price assignment? It's causing things like apparatus showing a generated value of 88, 102, 116, but then once on the company desk, sells for your priced over-ride instead, which is always a static amount unfortunately.

Just curious, I understand this mod hasn't been touched in 2 months, still think it's visually great otherwise!

**Comment by gamehog44** [comment]
Hi Roobotics. Since that is a fairly simple fix, I might be able to quickly create an update for that feature.

**Comment by gamehog44** [comment]
Added in commit 4aa05ed4f8865859b190b5aed15232c73cc58468.

**Comment by gamehog44** [comment]
Added in commit 4aa05ed4f8865859b190b5aed15232c73cc58468.

**Comment by Roobotics** [comment]
Awesome! Thanks for adding this intercompatible feature in so quickly. 

I've tested that selling at the company, functions as desired now as well.

**Comment by gamehog44** [comment]
Not a problem. Thanks for using the mod!
